id: P009429
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:38:25.015922
source_metadata:
  id: bdr:W2CZ7982
  title: དུས་ཀྱི་འཁོར་ལོའི་མངོན་རྟོགས་ཀྱི་དཀའ་བའི་གནད་མཁས་གྲུབ་དགེ་ལེགས་དཔལ་བཟང་ལ་དྲིས་པའི་ལན་
  author: ''
  volumes:
    0cfbd7ba7eac4f928f504f990c64f091:
      image_group_id: I1KG3781
      title: ''
      volume_number: 1
      total_pages: 76
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
