id: IF0F29497
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:29:52+00:00'
last_modified: '2022-06-08T10:58:31.347324+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7982
  title: དུས་ཀྱི་འཁོར་ལོའི་མངོན་རྟོགས་ཀྱི་དཀའ་བའི་གནད་མཁས་གྲུབ་དགེ་ལེགས་དཔལ་བཟང་ལ་དྲིས་པའི་ལན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4E8C:
      image_group_id: I1KG3781
      title: ''
      total_pages: 76
      order: 1
      base_file: 4E8C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
